# Page index
# If you add a page, you must also add it to the index here
nav:
    - index.md
    - Getting Started:
        - Step by Step: 'getting_started/step_by_step.md'
        - Introduction to the Editor: 'getting_started/editor_intro.md'
        - Coming From Unity/Unreal: 'getting_started/from_other_editors.md'
        - My First Game:
            - Map: 'getting_started/my_first_game/map.md'
            - Scripting: 'getting_started/my_first_game/functionality.md'
            - Shared Content: 'getting_started/my_first_game/shared_content.md'
    - Project Workflow:
        - Project Setup: 'project_workflow/project_setup.md'
        - Assets Workflow: 'project_workflow/assets_workflow.md'
        - Scripts Workflow: 'project_workflow/scripts_workflow.md'
        - Best Practices: 'project_workflow/best_practices.md'
        - Worst Practices: project_workflow/worst_practices.md
    - Scripting:
        - Overview: 'scripting/overview.md'
        - Lua Primer: 'scripting/lua_primer.md'
        - Debugging: 'scripting/debugging.md'
        - IDEs/Tools: scripting/ide_tools.md
        - Best Practices: 'scripting/best_practices.md'
        - Conventions: 'scripting/conventions.md'
        - Renaming: 'scripting/renaming.md'
    - Editor Manual:
        - Overview: 'editor/overview.md'
        - Editor Windows: 'editor/editor_windows.md'
        - Hotkeys: 'editor/hotkeys.md'
        - Templates: 'editor/templates.md'
        - Shared Content: 'editor/shared_content.md'
        - UI: 'editor/ui.md'
        - Audio: 'editor/audio.md'
        - Visual Effects: 'editor/vfx.md'
        - Animations: 'editor/animations.md'
        - Networking: 'editor/networking.md'
        - Abstract:
            - Vectors: 'editor/abstract/vectors.md'
            - Matrices: 'editor/abstract/matrices.md'
            - Raytracing: 'editor/abstract/raytracing.md'
            - Physics: 'editor/abstract/physics.md'
    - Tutorials (Empty):
        - Complete Games:
            - First Person Shooters:
                - Free For All: 'tutorials/full_games/fps/ffa_fps.md'
                - Team Deathmatch (with Abilities): 'tutorials/full_games/fps/tdm_abilities_fps.md'
                - Search and Destroy (with Classes): 'tutorials/full_games/fps/search_and_destroy_classes_fps.md'
            - RPG: 'tutorials/full_games/rpg.md'
        - Topics:
            - Game Rules: 
                - Freeform: 'tutorials/topics/game_rules/freeform.md'
                - Teams: 'tutorials/topics/game_rules/teams.md'
                - Rounds: 'tutorials/topics/game_rules/rounds.md'
                - Respawning: 'tutorials/topics/game_rules/respawning.md'
                - Abilities: 'tutorials/topics/game_rules/abilities.md'
            - Game Types:
                - Objective Based:
                    - Location Based:
                        - King of the Hill: 'tutorials/topics/game_types/objectives/location_based/king_of_the_hill.md'
                        - Payload: 'tutorials/topics/game_types/objectives/location_based/payload.md'
                    - Interactive:
                        - Capture the Flag: 'tutorials/topics/game_types/objectives/interactive/ctf.md'
                        - Search and Destroy: 'tutorials/topics/game_types/objectives/interactive/search_and_destroy.md'
                - First Person Shooter: 'tutorials/topics/game_types/fps.md'
                - Racing: 'tutorials/topics/game_types/racing.md'
                - RPG: 'tutorials/topics/game_types/rpg.md'
    - Examples: 'examples.md'
    - Community: 'community.md'
    - Core API:
        - Classes: 
            - Audio: 'audio.md'
                - Properties:
                    - isPlaying: 'isPlaying.md'
                    - length: 'length.md'
                    - currentPlaybackTime: 'currentPlaybackTime.md'
                    - isSpatializationDisabled: 'isSpatializationDisabled.md'
                    - isAutoPlayEnabled: 'isAutoPlayEnabled.md'
                    - isTransient: 'isTransient.md'
                    - isAutoRepeatEnabled: 'isAutoRepeatEnabled.md'
                    - pitch: 'pitch.md'
                    - volume: 'volume.md'
                    - radius: 'radius.md'
                    - falloff: 'falloff.md'
                - Functions: 
                    - Play: 'play.md'
                    - Stop: 'stop.md'
                    - FadeIn: 'fadein.md'
                    - FadeOut: 'fadeout.md'
        - Coming Soon: 'core_api/coming_soon.md'
        - Example Entry: 'core_api/example_entry.md'
        - Raw Source: 'core_api/raw_source.md'

# If you make a PR, no need to change data below this point

# Base material theme with customizations
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: 'blue grey' # desired -> #20232a
    accent: 'amber' # desired -> #ff9000

# Additional data
extra:
    core_version: 0.0.1-prealpha # CORE editor version this documentation applies to
    social:
    - type: 'discord' # unsupported
      link: 'ToDo'
    - type: 'reddit'
      link: 'ToDo'

markdown_extensions:
  - admonition # add info/warn/error admonitions
  - fontawesome_markdown # easily add fontawesome icons in markdown format
  - pymdownx.arithmatex # fancy math styling
  - pymdownx.betterem: # better bolding styles
      smart_enable: all
  - pymdownx.caret # insert and superscript
  - pymdownx.critic # editing allowed
  - pymdownx.details # admonition style details
  - pymdownx.emoji: # emojis
      emoji_generator: pymdownx.emoji.to_svg
  - pymdownx.inlinehilite # inline code highlighting
  - pymdownx.magiclink # autolinks and shorthand
  - pymdownx.mark # highlights
  - pymdownx.smartsymbols # special symbols like arrows
  - pymdownx.superfences # tabbed content (e.g. with code)
  - pymdownx.tasklist: # task list
      custom_checkbox: true
  - pymdownx.tilde # strike-through
  - codehilite: # highlight code blocks
      guess_lang: false # language has to be defined explicitly
  - toc: # add linking to headers
      permalink: true

# Site name
site_name: CORE Docs

# Add repository for easy editing
repo_url: https://gitlab.com/manticore-games/platform-documentation
edit_uri: edit/production/docs

# Metadata
site_description: Documentation for the CORE Engine
site_author: Manticore