# Page index
# If you add a page, you must also add it to the index here
nav:
    - index.md
    - Getting Started:
        - Editor: 'getting_started/editor_intro.md'
        - Art & Modeling in Core: 'getting_started/art.md'
        - Scripting: 'getting_started/scripting_intro.md'
        - Community Content: 'getting_started/community_content.md'
    - Tutorials:
        - Complete Game: 'tutorials/complete_game.md'
        - Terrain+: 'tutorials/terrain+.md'
        - Networking: 'tutorials/networking.md'
        - Gameplay:
            - Abilities: 'tutorials/gameplay/abilities.md'
            - Equipment: 'tutorials/gameplay/equipment.md'
            - Weapons: 'tutorials/gameplay/weapons.md'
        - UI: 'tutorials/ui.md'
    - Reference:
        - Useful Links: 'reference/links.md'
        - Scripting:
            - Lua Primer: 'reference/scripting/lua_primer.md'
            - Extensions: 'reference/scripting/extensions.md'
            - Conventions: 'reference/scripting/conventions.md'
        - Examples: 'reference/examples.md'
        - Core API: 'reference/core_api.md'
    - Community: 'community.md'

# If you make a PR, no need to change data below this point

# Base material theme with customizations
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: 'blue grey' # desired -> #20232a
    accent: 'amber' # desired -> #ff9000

# Additional data
extra:
    core_version: 0.0.1-prealpha # CORE editor version this documentation applies to
    social:
    - type: 'discord' # unsupported
      link: 'ToDo'
    - type: 'reddit'
      link: 'ToDo'

markdown_extensions:
  - admonition # add info/warn/error admonitions
  - fontawesome_markdown # easily add fontawesome icons in markdown format
  - pymdownx.arithmatex # fancy math styling
  - pymdownx.betterem: # better bolding styles
      smart_enable: all
  - pymdownx.caret # insert and superscript
  - pymdownx.critic # editing allowed
  - pymdownx.details # admonition style details
  - pymdownx.emoji: # emojis
      emoji_generator: pymdownx.emoji.to_svg
  - pymdownx.inlinehilite # inline code highlighting
  - pymdownx.magiclink # autolinks and shorthand
  - pymdownx.mark # highlights
  - pymdownx.smartsymbols # special symbols like arrows
  - pymdownx.superfences # tabbed content (e.g. with code)
  - pymdownx.tasklist: # task list
      custom_checkbox: true
  - pymdownx.tilde # strike-through
  - codehilite: # highlight code blocks
      guess_lang: false # language has to be defined explicitly
  - toc: # add linking to headers
      permalink: true

# Site name
site_name: CORE Docs

# Add repository for easy editing
repo_url: https://gitlab.com/manticore-games/platform-documentation
edit_uri: edit/production/docs

# Metadata
site_description: Documentation for the CORE Engine
site_author: Manticore