name: mkdocs

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2-beta
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - uses: actions/cache@v1
        id: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run lint

      - name: Install dependencies
        run: |
          git submodule update --init --recursive --depth=1
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build
        run: |
          mkdocs build
      - uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/production-publish' && runner.os == 'Linux'
        with:
          name: platform-documentation-production-publish-${{ github.sha }}
          path: site/
